config:
  watch:
    enabled: true
    delay: 10
    period: 5   ## check every 5 seconds

strat:
  activateFoo: true
  fooName: Hello
  fooHome: ${HOME}/config
  fooprops:  ${strat.key:bart}
  togglefeatures: true
  togglefeaturesA: false
  bar:
    barRules: 42
    barDouble: 33.3


